---
title: "kervel"
author: "Thuy Nguyen"
date: "5/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
gaussian_ker <- function(u)dnorm(u)
  
ker_box <-function(u) {ifelse(abs(u) <=1,1, 0)}
ker_Epanechnikov<- function(u){ifelse(abs(u) <=1,(3/4)*(1-u^2), 0)}
```

```{r}
poly <- function(x,y,ker, bw, xnew){
  n <- length(x)
  m <- length(xnew)
  #Weight
  sapply(x, function(xj){kernel((newx-xj)/h)})
  
  for (i in 1:m){
    X <-model.matrix(~poly((x - newx[i]), K, raw = T))
    W <-sapply(x, function(xj){ker((newx[i]-xj)/h)})
  }
}
  
```

# optimal bandwidth : using CV

```{r}
CV <- function(x,y,limits=NULL, k=10){
  
  x<- sort(x)
  y <- sort(y)
  
  fold <-as.integer(cut(sample(1:length(x)), breaks = k, labels= 1:k))
  
  mse <- function(h){
    e <- 1:k
    for (i in 1:k){
      e[i] <- sum((y[fold ==i] - local_poly(x[fold == -i],y[fold==-i], K, h = h,kernel = dnorm, newx=x[fold ==i]))^2)
    }
    return(mean(e))
  }
  MSE <- sapply(H, mse(h))
  
  H[which.min(MSE)]
  
  
 
}
```





# optimal bandwidth : using CV

```{r}
CV <- function(x,y,H){
  
  ord<- order(x)
  x <- x[ord]
  y<- y[ord]
  
  fold <-as.integer(cut(sample(1:length(x)), breaks = 5, labels= 1:5))
  
  mse <- function(h){
    e <- 1:5
    for (i in 1:5){
      e[i] <- sum((y[fold ==i] - local_poly(x[fold == -i],y[fold==-i], K, h = h,kernel = dnorm, newx=x[fold ==i]))^2)
    }
    return(mean(e))
  }
  MSE <- sapply(H, mse(h))
  
  H[which.min(MSE)]
  
  
 
}
```


```{r}
set.seed(70)
x <- sort(rnorm(50))
y <- 2*x^3-5*x^2 + rnorm(50, 0, 0.1)
length(y)
plot(local_poly(y, x,K=4, h = 10), x=x)
lines(x=x, y=y)
plot(y~x)
x1 <-runif(10, min = 5, max =10)
lines(local_poly(y, x, K=3, h = 100,  newx =x1 )~x1)
```


# Kernel

```{r}

```


